version: '3'
services:
  #Node Service
  frontend_node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_node
    restart: unless-stopped
    tty: true
    ports:
      - "80:3000"
    command: "npm run start"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge